"""empty message

Revision ID: 08630bdf791d
Revises: 07538fc3dc9b
Create Date: 2025-04-01 18:21:02.878934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08630bdf791d'
down_revision: Union[str, None] = '07538fc3dc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('user_profile', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_profile', 'hashed_password')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
